### ISSUE TITLE
Status and Advantages

### ISSUE THREAD

**Issue by GrosSacASac** [Kocisov/crab#6]
What is the status of this project ?

What are the advantage over using React ?

**Comment by kocisov** [comment]
Hello, thanks for the question.

The state of this project is something like done with a lot of space for making it better and also delayed by Firefox's support of Custom Elements which can be fixed by polyfills, but I'm not happy with them because I never get them to work properly, I don't know why 😞

It is not React replacement (as I use React almost every day) but more like a project to make HTMLElement class easier to work with and to have API that is familiar to React developers.
